= Cryptography

This chapter is meant to serve as a brief and gentle introduction to the cryptographic concepts often encountered in the field of security.
It is by no means exhaustive but it should provide a basis for a better understanding of why protocols are designed the way they are.
Cryptography is a method of scrambling data into non-readable text.
It allows us to transform data into a secure form so that unauthorized users cannot view it.

== Why do we need cryptography?

Cryptography is used to set up secure channels of communication, but it can also be used to provide non-repudiation of actions, basically leaving digital footprints that show someone did something.
This means that cryptography allows us to provide authentication, authorization, _and_ accounting (AAA).

By using a secure and _confidential_ encrypted channel we can be sure that anyone who intercepts our communications cannot "listen in." This helps prevents _man-in-the-middle (MITM)_ attacks.
Cryptography can also be used to provide _integrity_: proving that the data is valid. With cryptography you can provide a _signature_ for the data showing that the person who claims to have sent it really did send it.
Cryptography also allows for _non-repudiation_ as it can show that only one person was capable of sending a particular message. Lastly cryptography also allows us to perform authentication _without_ storing passwords in plaintext.
This is critical in an age where data breaches are increasingly common.

.Case Study: Equifax
****
https://www.ftc.gov/enforcement/cases-proceedings/refunds/equifax-data-breach-settlement[In September of 2017, Equifax announced a data breach the exposed the personal information of 147 million people.]
The original attack made use of an exploit in an outdated version of https://struts.apache.org/[Apache Struts] which was being used as part of Equifax's system for handling credit disputes from customers.
Once the attackers had gained access to internal Equifax servers, the began gathering as much information as they could from internal databases.

What is particularly egregious about this data breach is that passwords in many databases were stored in plaintext.
This means that the attackers were able to try the passwords and usernames on other services.
While it is important that users use different passwords for different services it is far more disturbing that a company as large as Equifax did not have the policies in place to use cryptography to mitigate the risks from such an enormous breach.
****

== Terminology

Going forward, it is important to address some common cryptography terms as they will be used frequently:

Plaintext::
    https://en.wikipedia.org/wiki/Plaintext[unencrypted information], data that is "in clear", or cleartext
Cipher::
    https://en.wikipedia.org/wiki/Cipher[an algorithm for performing encryption or decryption]
Ciphertext::
    data that has undergone encryption
Cryptographic algorithm::
    a series of steps to follow to encrypt or decrypt data
Public key::
    information (typically a byte array) that can be used to encrypt data such that only the owner of the matching _private key_ can unencrypt it
Private (secret) key::
    information (typically a byte array) that can be used to decrypt data encrypted using the corresponding public key

.Caesar Cipher
====
One of the most basic examples of encryption is the Caesar cipher, or substitution cipher.
It is easy to understand, compute, and trivial to crack.
Let's create a table that maps every letter in the alphabet to a different letter:

|===
|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z

|J|G|T|Q|X|Y|A|U|C|R|V|I|F|H|O|K|L|E|D|B|W|S|Z|M|N|P
|===

Now creating a message is simple a matter of performing the substitutions.
For example, `HELLO WORLD` becomes `UXIIO ZOEIQ`.

While this is simple to understand and set up, it is also very easy to break.
You could use a frequency attack, where you analyze a large chunk of encrypted text knowing that certain letters are more frequent than others.
By matching up the most frequently used ciphertext letters with their standard English equivalents you may quickly reach a solution.
You could also go through all permutations of the alphabet (4E26) and see what gives you the most English words.
The second attack is made much more feasible through computing.
====

== Keys

Typically a series of random bytes can be used as a key to either encrypt or decrypt data.
A key is used by a cryptographic algorithm to change plaintext to ciphertext.
Keys may also be asymmetric in that they can only be used to perform _one_ of the operations (either encryption or decryption).

It is important to have an idea of what factors make a _strong_ cryptographic key.
Length plays an important role.
The longer the key, the hard it is to _crack_ the encryption.
Likewise the randomness of the data in the key also makes it stronger.
If the byte sequence is somehow predictable, the length is irrelevant.
Finally we have the concept of a cryptoperiod or lifetime of a key.
If we are working with a system that frequently changes keys an attacker may not have enough time to crack it.

== Mathematical Foundation

Cryptography relies largely on the concept of one-way or trap door functions.
That is a process that is hard to compute in one direction, but easy to compute in the other.
For example it is much easier for a computer to multiply large numbers than to determine the factors of large numbers.
This is the foundation of the RSA algorithm.
https://www.cs.drexel.edu/~jpopyack/IntroCS/HW/RSAWorksheet.html[A simplified version of the algorithm] is shown below:

[source,text]
----
KEY GENERATION
p = a random prime number
q = a random prime number
N = p * q
r = (p - 1) * (q - 1)
K = a number which equals one when modded by r and can be factored
e = a factor of K that doesn't share factors with N
d = another factor of K that doesn't share factors with N
Your public key is N and e
Your private key is N and d 

ENCRYPTION
ciphertext = (cleartext**e)%N

DECRYPTION
cleartext = (ciphertext**d)%N

EXAMPLE
p = 7
q = 13
N = 7 * 13 = 91
r = 72
K = 145 (because 145%72 = 1)
e = 5
d = 29
Public Key = 91, 5
Private Key = 91, 29
cleartext = 72 ('H' in ASCII)
ciphertext = (72**5)%91 = 11 (encrypted using N and e)
cleartext = (11**29)%91 = 72 (decrypted using N and d) 
----

In order to _crack_ RSA you would need to be able to factor N into its two prime numbers.
While it is trivial in our simple example, imagine how difficult it would be to https://stackoverflow.com/questions/11832022/why-are-large-prime-numbers-used-in-rsa-encryption[factor a number with 1400 decimal digits,] the current recommended keysize for RSA.
You'll notice that the algorithm only requires exponentiation, multiplication, and modulus arithmetic.
At no point do you ever have to factor a large prime number to generate keys, encrypt, or decrypt.
You only have to perform that operation if you're trying to work backwards without the keys.

Other similar one-way function exist based on elliptical curves.
It turns out that motion along an elliptical curve can be described according to a start and end point and several iterations of a simple algorithm.
You can reconstruct the initial conditions if you know the start point, end point, and how many iterations it took.
If all you know is the start and end point you can't determine the initial conditions.

== Hashes

[svgbob, hash, width=300, float=right]
....
.------+                         .------+
| ---- |\       +---------+      | @2p[ |\
| ---- +-+      | _|___|_ |      | bB#7 +-+
| ------ | ---> | _|___|_ | ---> | #!@lsf |
| ------ |      |  |   |  |      | 2g9*qR |
| ------ |      +---------+      | xG4nVp |
'--------'                       '--------'
Plain Text     Hash Function     Hashed Text
....

A hashing algorithm is a one-way function that creates hashed text from plaintext.
It is often used for data validation as a relatively small hash _digest_ or _signature_ can demonstrate the integrity of a large block of data.
Hashes can also be used so that sensitive information does not have to be stored in cleartext.
By storing a hash of a password, you can check to see if the correct password was entered without storing the password itself.
In the case of a data breach only the hashes are leaked and the attacker does not have access to the passwords to try with other services.

Two main families of hash algorithms are used: MD5 and SHA.
MD5 produces a 128-bit hash value and is still often used to verify data integrity.
The algorithm is technically cryptographically broken, but you may still see it in use.
The SHA family of algorithms consists of SHA-1, SHA-2, and SHA-3:

* SHA-1: 160 bits, similar to MD5, designed by the NSA, no longer approved for cryptographic use
* SHA-2: SHA-256 and SHA-512, very common with the number indicating the block size, designed by the NSA
* SHA-3: non-NSA designed, not widely adopted, similar numbering scheme as SHA-2 (SHA3-256, etc.)

Dictionary based attacks against password hashes are fairly common.
Typically software is used which generates a hash for every word in the dictionary and then compares that hash to what is stored on the compromised machine.
One way to combat this is through salting or adding random bits to each password.
When salting the bits are stored with the hash.
This forces a dictionary based attack to actively generate the hashes based on what the salt is as opposed to using a stored table (rainbow table) of all the possible hashes.
It can make attacks go from instant to days or even years depending on the complexity of the password.

An even better way of combating attacks against hashes is through a secret salt or _pepper_.
A pepper is a random value that is added to the password but not stored with the resulting hash.
The random value can be stored in a separate medium such as a hardware Security Module.

== Symmetric Encryption

[svgbob, symmetric, width=550, float=left]
....
.------+                           .------+                           .------+
| ---- |\         ___              | ---- |\         ___              | ---- |\
| ---- +-+       /   \_______      | ---- +-+       /   \_______      | ---- +-+
| ------ | ---> (  A  ______/ ---> | ------ | ---> (  A  ______/ ---> | ------ |
| ------ |       \___/             | ------ |       \___/             | ------ |
| ------ |                         | ------ |                         | ------ |
'--------'                         '--------'                         '--------'
Plaintext        Encryption        Ciphertext       Decryption        Plaintext
....

Symmetric encryption is probably the simplest encryption to understand in that it only uses a single key (in this case our key is labelled 'A') to encrypt or decrypt data.
Both parties need to know the private key in order to communicate.
It does pose a security risk in that if the channel used for key exchange is insecure, all of the messages can be decrypted.
That being said, given that it is simpler than many other forms of encryption, it is often used for secure communication or storage.

.One-time-pad
====
One-time-pad (OTP) is a rare example of a pen and paper, symmetric encryption scheme that cannot be cracked.
The difficulty in OTP mirrors the difficulty with all symmetric encryption, namely that pre-shared keys need to be exchanged at some point.

Imagine that a prisoner wishes to send encrypted messages to someone outside the prison.
To do so, they will make use of a copy of Harry Potter and the Sorcerer's Stone that they have in their cell.
The message they want to send is "DIG UP THE GOLD".
They turn to "Chapter One: The Boy Who Lived" and look up the first twelve letters in the chapter: MR AND MRS DURS.
For each letter of their message, they convert it to its number in the alphabet: 4 9 7 21 16 20 8 5 7 15 12 4 (DIG UP THE GOLD).
They do the same for the key they looked up in their book: 13 18 1 14 4 13 18 19 4 21 18 19 (MR AND MRS DURS).
Finally they add the two numbers to get their ciphertext: 17 27 8 35 20 33 26 24 11 36 30 23.

If the prisoner sends that ciphertext to someone on the outside who knows that they key is the first chapter of Harry Potter and the Sorcerer's Stone, they will be able to subtract the key from each of the numbers in the ciphertext and discover the plaintext message.
While theoretically unbreakable, anybody else who has the key can recover the text as well.
This means that using common keys like popular books make it trivial for a man-in-the-middle to decode the ciphertext.
After all, the warden probably knows every book that the prisoner has in their cell.

OTP has been used by spy agencies, often for communications between individuals via dead-drops.
In this situation tables of random characters printed in duplicate are exchanged as the key.
====

== Asymmetric Encryption

[svgbob, asymmetric, width=700]
....
.------+                              .------+                               .------+
| ---- |\         ______              | ---- |\         _______              | ---- |\
| ---- +-+       /      \_______      | ---- +-+       /       \_______      | ---- +-+
| ------ | ---> ( Public ______/ ---> | ------ | ---> ( Private ______/ ---> | ------ |
| ------ |       \______/             | ------ |       \_______/             | ------ |
| ------ |                            | ------ |                             | ------ |
'--------'                            '--------'                             '--------'
Plaintext         Encryption          Ciphertext        Decryption           Plaintext
....

An asymmetric encryption algorithm has actually already been demonstrated in the <<Mathematical Foundation>> section.
Asymmetric encryption has a public key which can be published anywhere and used to encrypt messages that only the holder of the private key, which is not published, can unencrypt.
For example if you want to receive encrypted emails you may make your https://gnupg.org/[GNU Privacy Guard (GPG)] public key available a https://keyserver.ubuntu.com/[public key server].
This would allow anyone to look up your public key, encrypt a message that only you can read, and send you the ciphertext.
Asymmetric encryption gets around the difficulties of key exchange via an untrusted channel (like email).
Unfortunately the cost of such a useful system is that asymmetric algorithms tend to be much slower that their symmetric counterparts.

== Stream Ciphers

Stream ciphers encode data one symbol at a time and produces one ciphertext symbol for each cleartext symbol.
Given that you can often use some sort of block encryption with a significantly small block size, stream encryption is not used as often.
Technically the OTP example, when used one symbol at a time, is a stream cipher.
The keys come in one symbol at a time, the cleartext comes in one symbol at a time, and an operation is performed (addition in the case of the example) to create the ciphertext.
Given a suitable keysize and a well-researched algorithm, stream ciphers can be just as secure as block ciphers.
That being said a stream cipher is usually more consistent in its runtime characteristics and typically consumes less memory
Unfortunately there are not as many well-researched algorithms and widely used stream ciphers.

== Block Ciphers

Block ciphers takes the data in, in blocks and use cipher blocks of the same size to perform the encryption.
It is very popular and there are many secure algorithms to choose from.
Unfortunately if the input data doesn't fit neatly into blocks of the same size, padding may be required, which takes up more space/memory and reduces the speed of the cipher.
As such the block encryption is often less performant than stream encryption.

=== Block Cipher Modes of Operation

There are several ways you can create your cipher blocks and depending on how you do it, various attacks are possible:

==== Electronic Codebook (ECB)

[.float-group]
--

.https://commons.wikimedia.org/wiki/File:ECB_encryption.svg[WhiteTimberwolf (SVG version)], Public domain, via Wikimedia Commons
image::ecb.svg[width=600, float=right]

The simplest mode of operation, data is divided into blocks and each block is encoded using a key.
Since the blocks are encoded the same way, identical blocks will give identical ciphertexts.
This makes it easier, given enough data, to determine what the key is.
--

==== Cipher block chaining (CBC)

[.float-group]
--

.https://commons.wikimedia.org/wiki/File:CBC_encryption.svg[WhiteTimberwolf (SVG version)], Public domain, via Wikimedia Commons
image::cbc.svg[width=600, float=left]

Starting with an initialization vector (IV) each block is XORed with part of the ciphertext of the previous block to create a chain of ciphertext that is constantly changing.
This means that identical blocks will result in _different_ ciphertexts.
This is the most common mode of operation, its weaknesses being that the algorithm cannot be run in parallel (sorry modern processors) and that the IV is a common attack target.
--

==== Counter (CTR)

[.float-group]
--

.https://commons.wikimedia.org/wiki/File:CTR_encryption_2.svg[WhiteTimberwolf (SVG version)], Public domain, via Wikimedia Commons
image::ctr.svg[width=600, float=right]

Instead of using an IV, CTR uses a nonce (random number that is the same for all blocks) and counter.
The counter is incremented with each block, meaning this mode can function in parallel.
CTR mode solves the problems of ECB while still providing an algorithm that can run quickly on modern machines.
--
  
==== Galois/Counter Mode (GCM)

[.float-group]
--

.https://commons.wikimedia.org/w/index.php?curid=74845777[Gallois Counter Mode block diagram with initialization vector, pass:q[<br>]adapted from a diagram by NIST] is used under https://creativecommons.org/publicdomain/zero/1.0/deed.en[CC0 1.0]
image::gcm.svg[width=400, float=left]

GCM uses a counter like CTR, but does not make use of a nonce.
Instead an IV is used with the inititial counter.
GCM also generates a message authentication code (MAC) for each block to verify the integrity of the block.
This combination makes for a modern, robust algorithm that is gaining rapid adoption.
--

.Case Study: Exploiting Non-Rolling Codes
****
The importance of non-repeating codes, such as the counter codes used in the CTR and GCM block cipher modes of operation can be highlighted through analysis of another important technology that uses codes: keyless entry systems.
When garage door openers first came on to the market, the remote would broadcast a single code that the receiver was programmed to recognize as correct.
This meant that anyone listening in could easily get the code and replay the code to open the garage door with their own device.footnote:[In actuality the code space was so small that you could even easily create a device to cycle through all possible codes in under a minute.] To combat this, companies began using https://en.wikipedia.org/wiki/Rolling_code[rolling codes] in their remotes and receivers. Given the same seed a rolling code allows each device to generate a sequence of codes that are exactly the same. The remote will use the next code in a sequence every time the button is hit. The receiver will validate the recieved code if it matches any of the next several codes in the sequence (in case the button was hit a few times out of range). This effectively mitigates the replay attack.

Given that this was implemented in the 1980s with garage door remotes, you would assume car manufacturers employ the same technology in their remotes.
In a case of "everything old is new again" this isn't true.
https://github.com/HackingIntoYourHeart/Unoriginal-Rice-Patty/blob/main/README.md[Blake Berry (HackingIntoYourHeart) discovered that several makes and models of cars are actually still vulnerable to a replay attack.]

Sammy Kamkar also discovered a vulnerablility for rolling codes, named RollJam, which he demonstrated at DEF CON 23.
Kamkar's device jams signals sent by a keyfob, while recording the codes being sent.
Once it has two codes recorded, presumably from the victim pressing the button multiple times, it stops jamming, sends out the first code to unlock the car and stores the second code to unlock the car at a later time. 
****

== Encryption Examples

=== RSA

RSA is an asymmetric encryption standard developed in 1977 that is still very popular.
Its trapdoor function is based on the difficulty of factoring large numbers.
The name RSA comes from the names of the authors of the system: Ron Rivest, Adi Shamir, and Leonard Adleman.

=== Advanced Encryption Standard (AES)

AES is a symmetric block cipher developed in 1998 to supersede the less secure Data Encryption Standard (DES). 
AES works on 128 bit blocks of data, performing multiple rounds of substitution-permutation to encrypt data.
You will find AES used to encrypt network traffic (as is the case in a virtual private network), data stored to disk (disk encryption), or computer game data that is saved to storage.
AES is a _very_ common cipher.

=== Elliptic-curve Cryptography (ECC)

ECC is an asymmetric encryption scheme that is quite fast and easy to computer.
It is rapidly becoming the go to choice for digital signatures and key exchanges, gaining adopting starting in 2004.
ECC is based on the geometry of a pre-determined set of curves (some examples can be found http://www.secg.org/sec2-v2.pdf[here]), which can be used to create a trapdoor function.

=== Diffie-Hellman Key Exchange

[.float-group]
--

.https://commons.wikimedia.org/wiki/File:Diffie-Hellman_Key_Exchange.svg[Original schema: A.J. Han Vinck, University of Duisburg-EssenSVG version: Flugaal], Public domain, via Wikimedia Commons
image::dh.svg[width=300, float=right]

Given the slow nature of asymmetric algorithms, often an application such as a VPN will choose to use asymmetric cryptography to exchange a shared secret key and then use that secret key with a faster symmetric algorithm such as AES.
Diffie-Hellman does exactly that and was first published in 1976.
Diffie-Hellman key exchange uses the same mathematical concepts as RSA, exponentiation and modulus arithmetic, to great effect, but to visualize what is happening a metaphor of secret color mixing is used (see the included diagram).
It is important to remember that because the medium of exchange may be slow a DH key exchange is designed to generate minimal traffic.
--

=== Digital Certificates

A digital certificate is a set of credentials used to identify a company or an individual.
Since asymmetric encryption requires know a party's public key, a digital certificate includes that key as well as an ID of the owner.
The question then becomes how do you trust that the public key is _actually_ for the alleged owner?
That's where the issuing authority comes in.
A _certificate authority (CA)_ signs the certificate indicating that the ID and public_key are correct.
Certificates can be self-signed, but this sidesteps the trust placed in the CA and is often only used in testing.
Since most certificates are used for encrypting web traffic, Web browsers will typically warn you if a site is using a self-signed certificate.

Given how how many certificates need to be issued and the work that needs to be done to verify them, most certs are not issues by root CAs, but are actually issued by intermediate CAs.
Root CAs delegate the work to Intermediate CAs and indicate their trust in them by signing the intermediate CAs keys.
This creates a _chain of trust_ from the issued certificate (signed by the Intermediate CA) to the Intermediate CA (signed by the root CA) to the root CA (trusted by the browser).
Tools that use this chain of trust will keep the root CA certificates and update them from the companies that issue them as needed.

The certificate store is very important and while users rarely interact with it is often possible to install root CAs manually.
https://docs.telerik.com/fiddler/configure-fiddler/tasks/trustfiddlerrootcert[This is can be used to create a proxy that can decrypt HTTPS traffic for debugging] or for more nefarious purposes.
For this reason some applications, Facebook mobiles apps for example, maintain their own certificate store and prevent users from adding root CAs to it.

image::letsencrypt.svg[width=200, float=left, link=https://letsencrypt.org/]

So how do you get a certificate for your website?
The customer will generate a Certificate Signing Request (CSR) that includes the public key and their ID.
The CA will validate that the customer owns the website and build and sign the cert.
This whole process can be automated and performed for free via a tool called https://letsencrypt.org/[Let's Encrypt].

=== Blockchain

.https://commons.wikimedia.org/wiki/File:Bitcoin_logo.svg[Bitboy], Public domain, via Wikimedia Commons
image::btc.svg[width=150, float=right]

It is hard to talk about cryptography without addressing blockchains, one of the concepts behind cryptocurrencies.
A blockchain is a shared ledger (of transactions in the case of BitCoin) where blocks are constantly being added to add to the information being stored.
Periodically an new block is created, which includes a hash of the previous block and a hash of itself for the next block to reference.
By examining these hashes, you can prove the integrity each block and its position, thus making a publicly-available, mutually agreed upon accounting of what has occurred on the network.
Typically to prevent bad actors from adding block some sort of proof of work, a mathematically difficult operation, or proof of stake, an accounting of investment in the network, must be included when adding a block to the chain.

=== Trusted Platform Module (TPM) / Hardware Security Module (HSM)

These modules provide hardware specifically for use with encryption.
HSMs are removable modules while TPMs are motherboard chips.
Many ciphers rely on a reliable source of entropy (randomness) which these modules provide.
They can also significantly increase the speed at which cryptographic algorithms run by moving the operations to specialized hardware.
Lastly, these modules can be used to store keys _and_ make them only accessible via the module.
This can add an extra layer of security to prevent the keys from being easily copied.

=== Steganography

Steganography is the process of hiding data in something such that to a casual observer it cannot be detected.
Data can be hidden in audio, images, or even https://dl.packetstormsecurity.net/crypt/snow/description.html[plain text!].
The hidden data can also be encrypted if an additional layer of security is required.
In the field of security, malicious code may be hidden inside other files using steganographic techniques.
This makes it more difficult for tools to find them when searching storage.

== Lab: Hash it Out

A _hash_ is a one-way cryptographic function that produces a _unique_ set of characters for a given _message_.
In a perfect world, given a hash you should _not_ be able to determine what the original message was, but given a hash and the original message you can check that the hash matches the message.
Before we dive into the uses of a hash, lets try to further understand it by looking at a simple and consequently poor hashing algorithm.footnote:[This algorithm is so poor that it may be a stretch even to call it a hashing algorithm. That being said, it is being used as a tool to explain what hashes are.]

*Anagram Hash*

Let's assume we wanted to hash the message "Hello from Karl" so that we can have a string of characters the uniquely represent that phrase.
One way to do it would be to strip all the punctuation in the message, make everything lowercase, and then arrange all the letters alphabetically.
"Hello from Karl" becomes "aefhklllmoorr".
You can think of it like saying, "There is one 'a' in the message, one 'e' in the message, one 'f' in the message', one 'k' in the message, three 'l's in the message..."
Now our hash, "aefhklllmoorr", can be used to uniquely identify the phrase.

Now assume Karl wants to send us a message but he can't trust the person sending the message.
He could use the untrusted party to send us the message and then put the hash someplace public like on a website.
We could use the hash to know the message came from Karl _and_ if anyone else got the hash they would not be able to discern the message because a hash is a one-way function.
"aefhklllmoorr" reveals very little about the message, but it can be used to check its accuracy.

Hopefully this is beginning to show the power of hashes.
Now lets examine another very common usecase and find out exactly why this is a terrible algorithm.

Assume you run a website where a user uses a password to log in.
You want to make sure users are using their password when they log in, but you do not want to store the password on your website.
This is quite common.
If you website was breached you don't want to leak a bunch of people's passwords.
What do you do?
What you could do is store a hash of their password, hash the password when they try to login, and compare the hashes.
For example if our password was "password" using our basic hash algorithm the hash would be "adoprssw".
We could store "adoprssw" in our database, use it for comparison during login, and if someone were to ever steal the data in our database they wouldn't know that the original password is "password".
This may prevent an attacker from exploiting the fact that many people use the same password on multiple sites.

The problem is that there are many things that hash to "adoprssw" including "wordpass", "drowsaps", or even the hash we're storing: "adoprssw".
When multiple messages have the same hash it is referred to as a _collision_ and this particular algorithm is useless because it generates so many of them.

[IMPORTANT.deliverable]
====
What would the anagram hash of "AlwaysDancing" be?
====

Now that we understand what hashes do and to some extant how they are possible, lets look at a much more useful hash function.

*MD5*

For this section, we are going to be using Docker and a terminal.
https://docs.docker.com/get-docker/[Please follow these directions for installing Docker.]
For Windows you can use the https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701[Windows Terminal app] and in MacOS you can use the preinstalled Terminal app.
Gray boxes show the commands as typed into the terminal with typical output where possible.
Your prompt (the part shown before the command) may differ depending on your OS.

Start by running a BASH shell on a custom Linux container:

[source,console]
----
ryan@R90VJ3MK:/windir/c/Users/rxt1077/it230/docs$ docker run -it ryantolboom/hash <1>
root@8e0962021f85:/# <2>
----
<1> Here we are using the Docker run command interactively (-it) as this container runs bash by default
<2> Notice the new prompt showing that we are root on this container

MD5 is a message-digest algorithm that produces significantly better hashes than our Anagram algorithm.
Most Linux distributions include a simple utility for creating an MD5 hash based on a file's contents.
This command is named md5sum.
Typically this is used to detect if a file has been tampered with.
A website may provide links to download software as well as an MD5 hash of the files so that you know what you've downloaded is correct.
Similarly a security system may keep md5sums (MD5 hashes) of certain critical files to determine if they have been tampered with by malware.
Let's practice taking the md5sum of the `/etc/passwd` file:

[source,console]
----
root@8e0962021f85:/# md5sum /etc/passwd
9911b793a6ca29ad14ab9cb40671c5d7  /etc/passwd <1>
----
<1> The first part of this line is the MD5 hash, the second part is the file name

Now we'll make a file with _your_ first name in it and store it in /tmp/name.txt:

[source,console]
----
root@8e0962021f85:/# echo "<your_name>" >> /tmp/name.txt <1>
----
<1> Substitute your actual first name for <your_name>

[IMPORTANT.deliverable]
====
What is the md5sum of `/tmp/name.txt`?
====

For our final activity, lets take a look at some of the weaknesses of hashes.

*Hash Cracking*

Passwords in a Linux system are hashed and stored in the `/etc/shadow` file.
Let's print out the contents of that file to see how it looks:

[source,console]
----
root@7f978dd90746:/# cat /etc/shadow
root:*:19219:0:99999:7:::
daemon:*:19219:0:99999:7:::
bin:*:19219:0:99999:7:::
sys:*:19219:0:99999:7:::
sync:*:19219:0:99999:7:::
games:*:19219:0:99999:7:::
man:*:19219:0:99999:7:::
lp:*:19219:0:99999:7:::
mail:*:19219:0:99999:7:::
news:*:19219:0:99999:7:::
uucp:*:19219:0:99999:7:::
proxy:*:19219:0:99999:7:::
www-data:*:19219:0:99999:7:::
backup:*:19219:0:99999:7:::
list:*:19219:0:99999:7:::
irc:*:19219:0:99999:7:::
gnats:*:19219:0:99999:7:::
nobody:*:19219:0:99999:7:::
_apt:*:19219:0:99999:7:::
karl:$y$j9T$oR2ZofMTuH3dpEGbw6c/y.$TwfvHgCl4sIp0b28YTepJ3YVvl/3UyWKeLCmDV1tAd9:19255:0:99999:7::: <1>
----
<1> As you can see here the `karl` user has a long hash immediately after their username

One of the problems with hashes are that if people choose simple passwords, they can be easily cracked by a program that takes a wordlist of common passwords, generates their hashes, and then checks to see if the hash is the same.
While a hash may be a one-way function, it is still subject to this type of attack.
We're use a program called https://www.openwall.com/john/[John the Ripper] and do exactly that.

John the Ripper is already installed on this container along with a simple wordlist.
We will tell it to use the default wordlist to try and determine what the password is that matches karl's hash in `/etc/shadow`:

[source,console]
----
root@8e0962021f85:/# john --format=crypt --wordlist=/usr/share/john/password.lst /etc/shadow
Loaded 1 password hash (crypt, generic crypt(3) [?/64])
Press 'q' or Ctrl-C to abort, almost any other key for status
<karl's password>             (karl)
1g 0:00:00:01 100% 0.6211g/s 178.8p/s 178.8c/s 178.8C/s lacrosse..pumpkin
Use the "--show" option to display all of the cracked passwords reliably
Session completed
----

NOTE: Once john has cracked a password it will not show it if you run it again.
To _show_ the passwords that have already been cracked you must run the `--show` command with the file: `john --show /etc/shadow`

Given that the password is in the included common password wordlist, `/usr/share/john/password.lst`, you will quickly find that John the Ripper figures out that karl's password.
John the Ripper can also run incrementally though all the possible character combinations, but it takes much longer.
To help make these types of attacks more difficult, every hash in `/etc/shadow` is built off of a random number.
This number is called a _salt_ and is stored with the hash.
This means that instead of just trying one hash for each word in the wordlist, the hash cracker must try every possible salt for every word in the wordlist, slowing things down significantly.
Modern hash crackers may use https://en.wikipedia.org/wiki/Rainbow_table[rainbow tables] so that all of the possible hashes have already been computed.
These tables may take up terabytes of disk space, but can make cracking even complicated hashes much simpler.

Let's use a custom utility named `crypt` to show that we have the actual password.
We will start by printing out just the line in `/etc/shadow` that has karl's info.
We will use the `grep` command to limit out output to things that have `karl` in them:

[source,console]
----
root@7f978dd90746:/# cat /etc/shadow | grep karl
karl:$y$j9T$oR2ZofMTuH3dpEGbw6c/y.$TwfvHgCl4sIp0b28YTepJ3YVvl/3UyWKeLCmDV1tAd9:19255:0:99999:7:::
----

The first part of the shadow line is the username, karl.
The next part of the shadown line, immediately following the first colon, is the hash information.
The characters in between the first set of `$` is the version of the hashing algorithm being used, `y` for yescrypt in our case.
The characters in between the second set of `$` are the parameters passed to yescrypt which will always be `j9T` for us.
The characters in between the third set of `$` is your salt.
Finally the characters in between the fourth set of `$` is the hash.

The `crypt` utility calls the system https://man7.org/linux/man-pages/man3/crypt.3.html[`crypt`] command and prints the output.
Let's run this utility with the password we've cracked and the first three parts of the hash information from `/etc/shadow`.
If everything goes well, you should see hash output that matches what is in `/etc/shadow`:

[source,console]
----
root@7f978dd90746:/# crypt <karl's password> '$y$j9T$oR2ZofMTuH3dpEGbw6c/y.' <1>
$y$j9T$oR2ZofMTuH3dpEGbw6c/y.$TwfvHgCl4sIp0b28YTepJ3YVvl/3UyWKeLCmDV1tAd9
----
<1> Don't forget to use the actual password you cracked and put the hash info in single quotes

[IMPORTANT.deliverable]
====
Submit a screenshot with your lab showing that the output of the `crypt` command matches the hash in /etc/shadow
====

[#crypto_review]
== Review Questions

[qanda]
What is the difference between symmetric and asymmetric encryption? Give one common use case for each.::
    {empty}
What is a hash and what is it used for? How are hashes used in a blockchain?::
    {empty}
What is the difference between a stream cipher and a block cipher? Give one common use case for each.::
    {empty}
